spring:
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 128MB
  datasource:
    name: file-manager
    url: jdbc:mysql://example.com:3306/fileManager?autoReconnect=true&useUnicode=yes&useSSL=false&characterEncoding=UTF-8
    username: valord577
    password: valord577
    sql-script-encoding: UTF-8
    platform: mysql
    continue-on-error: false
    separator: //
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: select 'x'
      soft-min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-idle: 10
      max-idle: 10
      initial-size: 15
      max-total: 100

server:
  port: 65512

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

config:
  file-dir: image
  xml-location: /Users/valor/Desktop/liumu/file-manager/src/main/resources/white-list.xml
  token-ncr: zd//fI16CjKXCB9Of0tj0A==